const sharp = require("sharp");
const { toRawRGBA, fromRawRGBA } = require("./utils/raw");
const { chance, pick, randInt } = require("./utils/random");
const { applyWaveDistort } = require("./effects/waveDistort");
const { applyPerspective } = require("./effects/perspective");
const { warpToQuad } = require("./effects/homography");
const { generateBackground } = require("./effects/background");
const { applyVignette, applyFlashBloom, applyUnevenLighting } = require("./effects/lighting");
const { applySensorNoise } = require("./effects/noise");
const { applyLensBlur } = require("./effects/blur");

const SYNTHETIC_MARKER =
  "SYNTHETIC TEST FIXTURE - generated by ocr-robustness-fixtures, not a real receipt";

/** Places a raw RGBA image at (x, y) on a canvas with no warp, no interpolation. */
function placeFlat(srcRaw, srcW, srcH, x, y, canvasW, canvasH) {
  const out = Buffer.alloc(canvasW * canvasH * 4);
  for (let sy = 0; sy < srcH; sy++) {
    const dy = y + sy;
    if (dy < 0 || dy >= canvasH) continue;
    for (let sx = 0; sx < srcW; sx++) {
      const dx = x + sx;
      if (dx < 0 || dx >= canvasW) continue;
      const srcIdx = (sy * srcW + sx) * 4;
      const dstIdx = (dy * canvasW + dx) * 4;
      out[dstIdx] = srcRaw[srcIdx];
      out[dstIdx + 1] = srcRaw[srcIdx + 1];
      out[dstIdx + 2] = srcRaw[srcIdx + 2];
      out[dstIdx + 3] = 255;
    }
  }
  return out;
}

/**
 * Runs one clean receipt image through the full randomized degradation
 * pipeline and returns a JPEG buffer sized/compressed like a phone photo.
 */
async function processImage(inputBuffer, cfg) {
  let { data: srcRaw, width: srcW, height: srcH } = await toRawRGBA(inputBuffer);

  if (chance(cfg.waveDistort.probability)) {
    srcRaw = applyWaveDistort(srcRaw, srcW, srcH, cfg.waveDistort);
  }

  const padding = pick(cfg.background.paddingPct);
  const marginFactor = 1 + padding * 2 + 0.15; // extra room so rotation doesn't clip
  const canvasW = Math.round(srcW * marginFactor);
  const canvasH = Math.round(srcH * marginFactor);
  const rect = {
    x: (canvasW - srcW) / 2,
    y: (canvasH - srcH) / 2,
    w: srcW,
    h: srcH,
  };

  const background = generateBackground(canvasW, canvasH, cfg.background);

  const foreground = chance(cfg.perspective.probability)
    ? applyPerspective(srcRaw, srcW, srcH, rect, canvasW, canvasH, cfg.perspective)
    : warpToQuad(
        srcRaw,
        srcW,
        srcH,
        [
          [rect.x, rect.y],
          [rect.x + rect.w, rect.y],
          [rect.x + rect.w, rect.y + rect.h],
          [rect.x, rect.y + rect.h],
        ],
        canvasW,
        canvasH
      );

  let composed = await sharp(background, { raw: { width: canvasW, height: canvasH, channels: 4 } })
    .composite([{ input: foreground, raw: { width: canvasW, height: canvasH, channels: 4 }, blend: "over" }])
    .raw()
    .toBuffer();

  if (chance(cfg.vignette.probability)) {
    applyVignette(composed, canvasW, canvasH, pick(cfg.vignette.strength));
  }
  if (chance(cfg.flashBloom.probability)) {
    applyFlashBloom(composed, canvasW, canvasH, pick(cfg.flashBloom.strength));
  }
  if (chance(cfg.unevenLighting.probability)) {
    applyUnevenLighting(composed, canvasW, canvasH, pick(cfg.unevenLighting.strength));
  }
  if (chance(cfg.sensorNoise.probability)) {
    applySensorNoise(composed, canvasW, canvasH, pick(cfg.sensorNoise.amount));
  }

  let pipeline = fromRawRGBA(composed, canvasW, canvasH).flatten({ background: "#ffffff" });

  if (chance(cfg.lensBlur.probability)) {
    pipeline = applyLensBlur(pipeline, pick(cfg.lensBlur.sigma));
  }

  const longEdge = randInt(cfg.outputLongEdgePx[0], cfg.outputLongEdgePx[1]);
  pipeline = pipeline.resize({
    width: canvasW >= canvasH ? longEdge : null,
    height: canvasH > canvasW ? longEdge : null,
    fit: "inside",
  });

  const quality = randInt(cfg.jpegQuality[0], cfg.jpegQuality[1]);
  return pipeline
    .jpeg({ quality })
    .withMetadata({ exif: { IFD0: { ImageDescription: SYNTHETIC_MARKER } } })
    .toBuffer();
}

module.exports = { processImage };
